package io.github.gaming32.spigotonfabric.impl.entity;

import com.google.common.collect.ImmutableMap;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityTypes;
import org.bukkit.entity.EntityType;

import java.lang.reflect.Field;
import java.lang.reflect.ParameterizedType;
import java.util.Locale;

public class EntityClassToSpigotEntityType {
    public static final ImmutableMap<Class<? extends Entity>, EntityType> MAPPING = ImmutableMap.<Class<? extends Entity>, EntityType>builder()
        .put(net.minecraft.world.entity.item.EntityItem.class, EntityType.DROPPED_ITEM)
        .put(net.minecraft.world.entity.EntityExperienceOrb.class, EntityType.EXPERIENCE_ORB)
        .put(net.minecraft.world.entity.EntityAreaEffectCloud.class, EntityType.AREA_EFFECT_CLOUD)
        .put(net.minecraft.world.entity.monster.EntityGuardianElder.class, EntityType.ELDER_GUARDIAN)
        .put(net.minecraft.world.entity.monster.EntitySkeletonWither.class, EntityType.WITHER_SKELETON)
        .put(net.minecraft.world.entity.monster.EntitySkeletonStray.class, EntityType.STRAY)
        .put(net.minecraft.world.entity.projectile.EntityEgg.class, EntityType.EGG)
        .put(net.minecraft.world.entity.decoration.EntityLeash.class, EntityType.LEASH_HITCH)
        .put(net.minecraft.world.entity.decoration.EntityPainting.class, EntityType.PAINTING)
        .put(net.minecraft.world.entity.projectile.EntityTippedArrow.class, EntityType.ARROW)
        .put(net.minecraft.world.entity.projectile.EntitySnowball.class, EntityType.SNOWBALL)
        .put(net.minecraft.world.entity.projectile.EntityLargeFireball.class, EntityType.FIREBALL)
        .put(net.minecraft.world.entity.projectile.EntitySmallFireball.class, EntityType.SMALL_FIREBALL)
        .put(net.minecraft.world.entity.projectile.EntityEnderPearl.class, EntityType.ENDER_PEARL)
        .put(net.minecraft.world.entity.projectile.EntityEnderSignal.class, EntityType.ENDER_SIGNAL)
        .put(net.minecraft.world.entity.projectile.EntityPotion.class, EntityType.SPLASH_POTION)
        .put(net.minecraft.world.entity.projectile.EntityThrownExpBottle.class, EntityType.THROWN_EXP_BOTTLE)
        .put(net.minecraft.world.entity.decoration.EntityItemFrame.class, EntityType.ITEM_FRAME)
        .put(net.minecraft.world.entity.projectile.EntityWitherSkull.class, EntityType.WITHER_SKULL)
        .put(net.minecraft.world.entity.item.EntityTNTPrimed.class, EntityType.PRIMED_TNT)
        .put(net.minecraft.world.entity.item.EntityFallingBlock.class, EntityType.FALLING_BLOCK)
        .put(net.minecraft.world.entity.projectile.EntityFireworks.class, EntityType.FIREWORK)
        .put(net.minecraft.world.entity.monster.EntityZombieHusk.class, EntityType.HUSK)
        .put(net.minecraft.world.entity.projectile.EntitySpectralArrow.class, EntityType.SPECTRAL_ARROW)
        .put(net.minecraft.world.entity.projectile.EntityShulkerBullet.class, EntityType.SHULKER_BULLET)
        .put(net.minecraft.world.entity.projectile.EntityDragonFireball.class, EntityType.DRAGON_FIREBALL)
        .put(net.minecraft.world.entity.monster.EntityZombieVillager.class, EntityType.ZOMBIE_VILLAGER)
        .put(net.minecraft.world.entity.animal.horse.EntityHorseSkeleton.class, EntityType.SKELETON_HORSE)
        .put(net.minecraft.world.entity.animal.horse.EntityHorseZombie.class, EntityType.ZOMBIE_HORSE)
        .put(net.minecraft.world.entity.decoration.EntityArmorStand.class, EntityType.ARMOR_STAND)
        .put(net.minecraft.world.entity.animal.horse.EntityHorseDonkey.class, EntityType.DONKEY)
        .put(net.minecraft.world.entity.animal.horse.EntityHorseMule.class, EntityType.MULE)
        .put(net.minecraft.world.entity.projectile.EntityEvokerFangs.class, EntityType.EVOKER_FANGS)
        .put(net.minecraft.world.entity.monster.EntityEvoker.class, EntityType.EVOKER)
        .put(net.minecraft.world.entity.monster.EntityVex.class, EntityType.VEX)
        .put(net.minecraft.world.entity.monster.EntityVindicator.class, EntityType.VINDICATOR)
        .put(net.minecraft.world.entity.monster.EntityIllagerIllusioner.class, EntityType.ILLUSIONER)
        .put(net.minecraft.world.entity.vehicle.EntityMinecartCommandBlock.class, EntityType.MINECART_COMMAND)
        .put(net.minecraft.world.entity.vehicle.EntityBoat.class, EntityType.BOAT)
        .put(net.minecraft.world.entity.vehicle.EntityMinecartRideable.class, EntityType.MINECART)
        .put(net.minecraft.world.entity.vehicle.EntityMinecartChest.class, EntityType.MINECART_CHEST)
        .put(net.minecraft.world.entity.vehicle.EntityMinecartFurnace.class, EntityType.MINECART_FURNACE)
        .put(net.minecraft.world.entity.vehicle.EntityMinecartTNT.class, EntityType.MINECART_TNT)
        .put(net.minecraft.world.entity.vehicle.EntityMinecartHopper.class, EntityType.MINECART_HOPPER)
        .put(net.minecraft.world.entity.vehicle.EntityMinecartMobSpawner.class, EntityType.MINECART_MOB_SPAWNER)
        .put(net.minecraft.world.entity.monster.EntityCreeper.class, EntityType.CREEPER)
        .put(net.minecraft.world.entity.monster.EntitySkeleton.class, EntityType.SKELETON)
        .put(net.minecraft.world.entity.monster.EntitySpider.class, EntityType.SPIDER)
        .put(net.minecraft.world.entity.monster.EntityGiantZombie.class, EntityType.GIANT)
        .put(net.minecraft.world.entity.monster.EntityZombie.class, EntityType.ZOMBIE)
        .put(net.minecraft.world.entity.monster.EntitySlime.class, EntityType.SLIME)
        .put(net.minecraft.world.entity.monster.EntityGhast.class, EntityType.GHAST)
        .put(net.minecraft.world.entity.monster.EntityPigZombie.class, EntityType.ZOMBIFIED_PIGLIN)
        .put(net.minecraft.world.entity.monster.EntityEnderman.class, EntityType.ENDERMAN)
        .put(net.minecraft.world.entity.monster.EntityCaveSpider.class, EntityType.CAVE_SPIDER)
        .put(net.minecraft.world.entity.monster.EntitySilverfish.class, EntityType.SILVERFISH)
        .put(net.minecraft.world.entity.monster.EntityBlaze.class, EntityType.BLAZE)
        .put(net.minecraft.world.entity.monster.EntityMagmaCube.class, EntityType.MAGMA_CUBE)
        .put(net.minecraft.world.entity.boss.enderdragon.EntityEnderDragon.class, EntityType.ENDER_DRAGON)
        .put(net.minecraft.world.entity.boss.wither.EntityWither.class, EntityType.WITHER)
        .put(net.minecraft.world.entity.ambient.EntityBat.class, EntityType.BAT)
        .put(net.minecraft.world.entity.monster.EntityWitch.class, EntityType.WITCH)
        .put(net.minecraft.world.entity.monster.EntityEndermite.class, EntityType.ENDERMITE)
        .put(net.minecraft.world.entity.monster.EntityGuardian.class, EntityType.GUARDIAN)
        .put(net.minecraft.world.entity.monster.EntityShulker.class, EntityType.SHULKER)
        .put(net.minecraft.world.entity.animal.EntityPig.class, EntityType.PIG)
        .put(net.minecraft.world.entity.animal.EntitySheep.class, EntityType.SHEEP)
        .put(net.minecraft.world.entity.animal.EntityCow.class, EntityType.COW)
        .put(net.minecraft.world.entity.animal.EntityChicken.class, EntityType.CHICKEN)
        .put(net.minecraft.world.entity.animal.EntitySquid.class, EntityType.SQUID)
        .put(net.minecraft.world.entity.animal.EntityWolf.class, EntityType.WOLF)
        .put(net.minecraft.world.entity.animal.EntityMushroomCow.class, EntityType.MUSHROOM_COW)
        .put(net.minecraft.world.entity.animal.EntitySnowman.class, EntityType.SNOWMAN)
        .put(net.minecraft.world.entity.animal.EntityOcelot.class, EntityType.OCELOT)
        .put(net.minecraft.world.entity.animal.EntityIronGolem.class, EntityType.IRON_GOLEM)
        .put(net.minecraft.world.entity.animal.horse.EntityHorse.class, EntityType.HORSE)
        .put(net.minecraft.world.entity.animal.EntityRabbit.class, EntityType.RABBIT)
        .put(net.minecraft.world.entity.animal.EntityPolarBear.class, EntityType.POLAR_BEAR)
        .put(net.minecraft.world.entity.animal.horse.EntityLlama.class, EntityType.LLAMA)
        .put(net.minecraft.world.entity.projectile.EntityLlamaSpit.class, EntityType.LLAMA_SPIT)
        .put(net.minecraft.world.entity.animal.EntityParrot.class, EntityType.PARROT)
        .put(net.minecraft.world.entity.npc.EntityVillager.class, EntityType.VILLAGER)
        .put(net.minecraft.world.entity.boss.enderdragon.EntityEnderCrystal.class, EntityType.ENDER_CRYSTAL)
        .put(net.minecraft.world.entity.animal.EntityTurtle.class, EntityType.TURTLE)
        .put(net.minecraft.world.entity.monster.EntityPhantom.class, EntityType.PHANTOM)
        .put(net.minecraft.world.entity.projectile.EntityThrownTrident.class, EntityType.TRIDENT)
        .put(net.minecraft.world.entity.animal.EntityCod.class, EntityType.COD)
        .put(net.minecraft.world.entity.animal.EntitySalmon.class, EntityType.SALMON)
        .put(net.minecraft.world.entity.animal.EntityPufferFish.class, EntityType.PUFFERFISH)
        .put(net.minecraft.world.entity.animal.EntityTropicalFish.class, EntityType.TROPICAL_FISH)
        .put(net.minecraft.world.entity.monster.EntityDrowned.class, EntityType.DROWNED)
        .put(net.minecraft.world.entity.animal.EntityDolphin.class, EntityType.DOLPHIN)
        .put(net.minecraft.world.entity.animal.EntityCat.class, EntityType.CAT)
        .put(net.minecraft.world.entity.animal.EntityPanda.class, EntityType.PANDA)
        .put(net.minecraft.world.entity.monster.EntityPillager.class, EntityType.PILLAGER)
        .put(net.minecraft.world.entity.monster.EntityRavager.class, EntityType.RAVAGER)
        .put(net.minecraft.world.entity.animal.horse.EntityLlamaTrader.class, EntityType.TRADER_LLAMA)
        .put(net.minecraft.world.entity.npc.EntityVillagerTrader.class, EntityType.WANDERING_TRADER)
        .put(net.minecraft.world.entity.animal.EntityFox.class, EntityType.FOX)
        .put(net.minecraft.world.entity.animal.EntityBee.class, EntityType.BEE)
        .put(net.minecraft.world.entity.monster.hoglin.EntityHoglin.class, EntityType.HOGLIN)
        .put(net.minecraft.world.entity.monster.piglin.EntityPiglin.class, EntityType.PIGLIN)
        .put(net.minecraft.world.entity.monster.EntityStrider.class, EntityType.STRIDER)
        .put(net.minecraft.world.entity.monster.EntityZoglin.class, EntityType.ZOGLIN)
        .put(net.minecraft.world.entity.monster.piglin.EntityPiglinBrute.class, EntityType.PIGLIN_BRUTE)
        .put(net.minecraft.world.entity.animal.axolotl.Axolotl.class, EntityType.AXOLOTL)
        .put(net.minecraft.world.entity.decoration.GlowItemFrame.class, EntityType.GLOW_ITEM_FRAME)
        .put(net.minecraft.world.entity.GlowSquid.class, EntityType.GLOW_SQUID)
        .put(net.minecraft.world.entity.animal.goat.Goat.class, EntityType.GOAT)
        .put(net.minecraft.world.entity.Marker.class, EntityType.MARKER)
        .put(net.minecraft.world.entity.animal.allay.Allay.class, EntityType.ALLAY)
        .put(net.minecraft.world.entity.vehicle.ChestBoat.class, EntityType.CHEST_BOAT)
        .put(net.minecraft.world.entity.animal.frog.Frog.class, EntityType.FROG)
        .put(net.minecraft.world.entity.animal.frog.Tadpole.class, EntityType.TADPOLE)
        .put(net.minecraft.world.entity.monster.warden.Warden.class, EntityType.WARDEN)
        .put(net.minecraft.world.entity.animal.camel.Camel.class, EntityType.CAMEL)
        .put(net.minecraft.world.entity.Display.BlockDisplay.class, EntityType.BLOCK_DISPLAY)
        .put(net.minecraft.world.entity.Interaction.class, EntityType.INTERACTION)
        .put(net.minecraft.world.entity.Display.ItemDisplay.class, EntityType.ITEM_DISPLAY)
        .put(net.minecraft.world.entity.animal.sniffer.Sniffer.class, EntityType.SNIFFER)
        .put(net.minecraft.world.entity.Display.TextDisplay.class, EntityType.TEXT_DISPLAY)
        .put(net.minecraft.world.entity.monster.breeze.Breeze.class, EntityType.BREEZE)
        .put(net.minecraft.world.entity.projectile.WindCharge.class, EntityType.WIND_CHARGE)
        .put(net.minecraft.world.entity.projectile.EntityFishingHook.class, EntityType.FISHING_HOOK)
        .put(net.minecraft.world.entity.EntityLightning.class, EntityType.LIGHTNING)
        .put(net.minecraft.world.entity.player.EntityHuman.class, EntityType.PLAYER)
        .build();

    public static void main(String[] args) throws Exception {
        for (final EntityType entityType : EntityType.values()) {
            if (entityType == EntityType.UNKNOWN) continue;
            final Field vanilla = EntityTypes.class.getDeclaredField(entityType.getName().toUpperCase(Locale.ROOT));
            final String vanillaClass = ((ParameterizedType)vanilla.getGenericType()).getActualTypeArguments()[0]
                .getTypeName().replace('$', '.');
            System.out.printf(".put(%s.class, EntityType.%s)\n", vanillaClass, entityType.name());
        }
    }
}
